---
- name: Setup Home infrastructure
  hosts: all
  become: yes
  vars_files:
    - home.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:

    - name: Create docker group if it doesn't exist
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: borg  # Replace with your actual username
        groups: docker
        append: yes


    #=========================================
    # Plex Media Server
    - name: Create mount point directory for Plex config
      file:
        path: /mnt/lab-docker-config-local/plex
        state: directory


    - name: Create mount point directory for media
      file:
        path: "/mnt/media"
        state: directory

    - name: Mount SMB share for Plex media
      mount:
        src: //192.168.128.74/K-DAS/Media
        path: /mnt/media
        fstype: cifs
        opts: username={{ smb_username }},password={{ smb_password }},vers=3.0
        state: mounted

    #=========================================
    # Portainer
    - name: Create mount point directory for Portainer config
      file:
        path: /mnt/lab-docker-config-local/portainer
        state: directory

    #=========================================
    # Heimdall
    - name: Create mount point directory for Heimdall config
      file:
        path: /mnt/lab-docker-config-local/heimdall
        state: directory

    #=========================================
    # Jellyfin
    - name: Create mount point directory for Jellyfin config
      file:
        path: /mnt/lab-docker-config-local/jellyfin
        state: directory

    #=========================================
    # Emby
    - name: Create mount point directory for Emby config
      file:
        path: /mnt/lab-docker-config-local/emby
        state: directory

    #=========================================
    # Folding@Home
    - name: Create mount point directory for Folding@Home config
      file:
        path: /mnt/lab-docker-config-local/foldingathome
        state: directory

    #=========================================
    # AnythingLLM
    - name: Create mount point directory for AnythingLLM@Home config
      file:
        path:  /mnt/lab-docker-config-local/anythingllm
        state: directory

    #=========================================
    # Execute the docker files
    - name: Copy Docker Compose file
      copy:
        src: ./home-infrastructure-compose.yaml
        dest: /opt/docker-compose/home-infrastructure-compose.yaml

    - name: Start Docker Compose
      command: docker-compose -f /opt/docker-compose/home-infrastructure-compose.yaml up -d
      args:
        chdir: /opt/docker-compose

    #=========================================
    # Cleanup
    - name: Delete Docker Compose file from target server
      file:
        path: /opt/docker-compose/home-infrastructure-compose.yaml
        state: absent
