version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: Portainer
    networks:
      - home_network
    ports:
      - "9000:9000"  # Port mapping for Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/lab-docker-config/portainer:/data
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: Heimdall
    networks:
      - home_network
    ports:
      - "8008:80"  # Port mapping for Heimdall
    volumes:
      - /mnt/lab-docker-config-local/heimdall:/config
    restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    networks:
      - home_network
    ports:
      - "8384:8384"  # Port mapping for Syncthing GUI
      - "22000:22000"  # Port mapping for Syncthing listening port
      - "21027:21027/udp"  # Port mapping for Syncthing discovery port
    volumes:
      - /mnt/lab-docker-config-local/syncthing:/config
      - /mnt/syncthing/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - home_network
    ports:
      - "8096:8096"  # Port mapping for Jellyfin
    volumes:
      - /mnt/lab-docker-config-local/jellyfin:/config
      - /mnt/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    restart: unless-stopped

  emby:
    image: linuxserver/emby
    container_name: emby
    networks:
      - home_network
    ports:
      - "8097:8096"  # Port mapping for Emby
    volumes:
      - /mnt/lab-docker-config-local/emby:/config
      - /mnt/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    restart: unless-stopped 

  foldingathome:
    image: linuxserver/foldingathome
    container_name: foldingathome
    networks:
      - home_network
    ports:
      - "7396:7396"  # Port mapping for Folding@home Web Control
    volumes:
      - /mnt/lab-docker-config-local/foldingathome:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - ACCOUNT_TOKEN=bfL8RbfMvec0Jveca6sQda6s4KG2W4KGICde7ICd_t8
      - MACHINE_NAME=Mariette
      - GPU=true  # Enable GPU folding
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Required capabilities
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    runtime: nvidia
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - home_network
    ports:
      - "11434:11434"
    volumes:
      - /mnt/lab-docker-config-local/ollama:/config
      - /mnt/lab-docker-config-local/ollama-models:/root/.ollama
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    runtime: nvidia
    restart: unless-stopped

  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="G7Ez$wmD6z&$%mX^X!VyeKuAisMifh"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://172.16.100.4:11434
      - OLLAMA_MODEL_PREF=llama3.1
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://172.16.100.4:11434
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      # Add any other keys here for services or settings
      # you can find in the docker/.env.example file
    volumes:
      - /mnt/lab-docker-config-local/anythingllm:/app/server/storage
    restart: always

networks:
  home_network:
    external: true