---
- name: Setup NVIDIA GPU in Docker on Ubuntu
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Add NVIDIA Docker GPG key
      shell: |
        curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -

    - name: Add NVIDIA Docker repository
      shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present

    - name: Install NVtop
      apt:
        name: nvtop
        state: present

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Verify NVIDIA Docker installation
      command: |
        sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
      register: result

    - name: Display NVIDIA Docker verification result
      debug:
        msg: "{{ result.stdout }}"