- hosts: localhost
  tasks:
    - name: Upgrade all Homebrew packages
      homebrew:
        upgrade_all: yes

    - name: Install dockutil
      homebrew:
        name: dockutil
        state: present
  
    - name: Install Bitwarden
      homebrew_cask:
        name: bitwarden
        state: present

    - name: Add Bitwarden to Dock
      command:
        cmd: dockutil --add /Applications/Bitwarden.app --replacing Bitwarden

    - name: Install Dropbox
      homebrew_cask:
        name: dropbox
        state: present

    - name: Install Omni DiskSweeper
      homebrew_cask:
        name: omnidisksweeper
        state: present

    - name: Install Google Drive
      homebrew_cask:
        name: google-drive
        state: present

    - name: Install Remote Desktop
      homebrew_cask:
        name: microsoft-remote-desktop
        state: present

    - name: Install Warp
      homebrew_cask:
        name: warp
        state: present

    - name: Add Warp to Dock
      command:
        cmd: dockutil --add /Applications/Warp.app --replacing Warp

    - name: Install BBEdit
      homebrew_cask:
        name: bbedit
        state: present

    - name: Install MAS
      homebrew:
        name: mas
        state: present

    - name: Install NMAP
      homebrew:
        name: nmap
        state: present

    - name: Install ffmpeg
      homebrew:
        name: ffmpeg
        state: present

    - name: Install AIchat
      homebrew:
        name: aichat
        state: present

    - name: Install Btop
      homebrew:
        name: btop
        state: present

    - name: Install cURL
      homebrew:
        name: curl
        state: present

    - name: Install Flac
      homebrew:
        name: flac
        state: present

    - name: Install Btop
      homebrew:
        name: btop
        state: present

    - name: Install GitHub command line utility
      homebrew:
        name: gh
        state: present

    - name: Install remind
      homebrew:
        name: remind
        state: present
    
    - name: Install Htop
      homebrew:
        name: htop
        state: present
    
    - name: Install ShhPass
      homebrew:
        name: sshpass
        state: present
    
    - name: Install Mac App Store utility
      homebrew:
        name: mas
        state: present
    
    - name: Install wget
      homebrew:
        name: wget
        state: present
    
    - name: Install ShhPass
      homebrew:
        name: sshpass
        state: present
    
    - name: Install Wireshark
      homebrew_cask:
        name: wireshark
        state: present
    
    - name: Install YouTube downloader
      homebrew:
        name: yt-dlp
        state: present
