- hosts: localhost
  tasks:
    - name: Install geerlingguy.mac role
        ansible.builtin.command:
          cmd: ansible-galaxy install geerlingguy.mac
        warn: no

    - name: Install Bitwarden
      homebrew_cask:
        name: bitwarden
        state: present

    - name: Add Bitwarden to Dock
      geerlingguy.mac.dock:
        name: Bitwarden
        path: /Applications/Bitwarden.app
        state: present

    - name: Install Dropbox
      homebrew_cask:
        name: dropbox
        state: present

    - name: Install Remote Desktop
      homebrew_cask:
        name: microsoft-remote-desktop
        state: present

    - name: Install Warp
      homebrew_cask:
        name: warp
        state: present

    - name: Install BBEdit
      homebrew_cask:
        name: bbedit
        state: present

    - name: Install MAS
      homebrew:
        name: mas
        state: present

    - name: Install NMAP
      homebrew:
        name: nmap
        state: present

    - name: Install ffmpeg
      homebrew:
        name: ffmpeg
        state: present

    - name: Install AIchat
      homebrew:
        name: aichat
        state: present

    - name: Install Btop
      homebrew:
        name: btop
        state: present

    


    
    