- hosts: localhost
  tasks:
    - name: Install Bitwarden
      homebrew_cask:
        name: bitwarden
        state: present

    - name: Install Dropbox
      homebrew_cask:
        name: dropbox
        state: present

    - name: Install Remote Desktop
      homebrew_cask:
        name: microsoft-remote-desktop
        state: present

    - name: Install MS Edge Browser
      homebrew_cask:
        name: microsoft-edge
        state: present