- hosts: localhost
  tasks:
    - name: Check if Bitwarden is installed
      command: brew list --cask bitwarden
      register: bitwarden_installed
      ignore_errors: true

    - name: Install Bitwarden
      command: brew install --cask bitwarden
      when: bitwarden_installed.rc != 0

    - name: Download Adobe Creative Cloud installer
      get_url:
        url: https://ccmdls.adobe.com/AdobeProducts/KCCC/1/osx10/ACCCx4_8_1_435.dmg
        dest: /tmp/ACCCx4_8_1_435.dmg

    - name: Mount the DMG
      command: hdiutil attach /tmp/ACCCx4_8_1_435.dmg

    - name: Install Adobe Creative Cloud
      command: installer -pkg /Volumes/CC/Install.app/Contents/Resources/Adobe\ Creative\ Cloud\ Installer.pkg -target /
      become: yes

    - name: Unmount the DMG
      command: hdiutil detach /Volumes/CC